export default {
    CONNECTION_OPEN: 'CONNECTION_OPEN',
    GUILD_CREATE: 'GUILD_CREATE',
    GUILD_DELETE: 'GUILD_DELETE',
    GUILD_MEMBER_LIST_UPDATE: 'GUILD_MEMBER_LIST_UPDATE',
    ONLINE_GUILD_MEMBER_COUNT_UPDATE: 'ONLINE_GUILD_MEMBER_COUNT_UPDATE'
};
